### ISSUE TITLE
Should automatically determine the current biennium based on the date

### ISSUE THREAD

**Issue by eldang** [eldang/Washington-HB-finder#5]
This won't matter for a while, but assuming the URL formats don't change by 2019 this would let the page stay useful then.

**Comment by rainhead** [comment]
Taking this as an easy first task!

**Comment by rainhead** [comment]
Oh also I totally borked this.

**Comment by eldang** [comment]
Heh, that's at least partly my fault for not doing a local test before merging.  Will do better next time.
